In [1]:
import numpy as np

In [4]:
np.random.rand(3,4)

array([[0.455, 0.222, 0.387, 0.492],
       [0.055, 0.254, 0.195, 0.486],
       [0.171, 0.167, 0.66 , 0.094]])

In [3]:
np.set_printoptions(precision=3)

In [8]:
np.random.randint(30, size = (5,6))

array([[ 0,  9, 10, 18,  1,  0],
       [24, 21,  9, 21, 24,  3],
       [13, 20, 28,  8, 15,  1],
       [18, 23, 24, 28, 14, 13],
       [18, 18,  2,  7, 13, 19]])

In [9]:
np.random.randint(0,30,7)

array([29,  3,  5, 11, 25,  8,  1])

In [10]:
arr_1 = np.arange(100)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.random.shuffle(arr_1)
arr_1

array([29, 81, 15, 86, 64, 18, 56, 84, 13, 74, 51, 65, 28, 20, 34, 85, 78,
       48, 32, 68, 95,  9, 17, 16,  3, 54, 72, 77, 69, 38, 14, 25, 39, 21,
        4,  1, 10, 40, 44,  2, 75, 73, 24, 59, 76, 52, 93,  6,  8, 37, 92,
       35, 22, 47, 61, 55, 58, 67, 42, 12, 36, 80, 45, 94, 19, 50, 62, 71,
       27, 82, 89, 99, 91,  5,  7, 43, 41,  0, 57, 26, 49, 63, 66, 87, 97,
       31, 30, 60, 70, 11, 79, 96, 83, 53, 46, 98, 23, 33, 88, 90])

In [20]:
np.random.seed(2)

In [21]:
np.random.rand(3,3)

array([[0.436, 0.026, 0.55 ],
       [0.435, 0.42 , 0.33 ],
       [0.205, 0.619, 0.3  ]])